simulation_time: 0.6
steps: 288
brax_substeps: 2
radius: 0.1
init_pos:
  - -0.5
  - 1.
init_vel:
  - 5.
  - -5.
ctrl_input:
  - 0.
  - 0.
target:
  - -2.0
  - 1.5
wall_x: 1.75
elasticity: 0.92
customized_kn: 1.e+4 # for soft model
customized_kd: 1.e+1
customized_mu: 0.00
learning_rate: 0.01
is_train: True
train_iters: 1000
method: symplectic_euler # for intergration in diffcosim
toi: True
result_dir: results
render_difftaichi: False
verbose: False
