simulation_time: 1.0
steps: 480
brax_substeps: 2
radius: 0.2
target:
  - 0.0
  - 0.0
epsilon: 0.1
elasticity: 1.0
customized_kn: 1.e+4 # for soft model
# customized_kd: 1.e+1
customized_mu: 0.00
learning_rate: 10.
is_train: True
train_iters: 1000
method: symplectic_euler # for intergration in diffcosim
toi: True # for convex_opt and difftaichi
result_dir: results
render_difftaichi: False
verbose: False
